Cinnamon1.6/CoverflowAltTab@dmo60.de/manager.js      usr/share/cinnamon/extensions/CoverflowAltTab@dmo60.de
Cinnamon1.6/CoverflowAltTab@dmo60.de/metadata.json   usr/share/cinnamon/extensions/CoverflowAltTab@dmo60.de
Cinnamon1.6/CoverflowAltTab@dmo60.de/switcher.js     usr/share/cinnamon/extensions/CoverflowAltTab@dmo60.de
Cinnamon1.6/CoverflowAltTab@dmo60.de/stylesheet.css  usr/share/cinnamon/extensions/CoverflowAltTab@dmo60.de
Cinnamon1.6/CoverflowAltTab@dmo60.de/extension.js    usr/share/cinnamon/extensions/CoverflowAltTab@dmo60.de
